name: Create PR for Todo Update

on:
  workflow_dispatch:
    inputs:
      item:
        description: 'Item to add to the todo list'
        required: true
        default: 'Review PRs'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Capture Inputs
        run: |
          echo "ACTOR_NAME=${{ github.actor }}" >> $GITHUB_ENV
          echo "ITEM=${{ github.event.inputs.item }}" >> $GITHUB_ENV

      - name: Add item to todo list
        run: echo "${{ github.event.inputs.item }}" >> todo.txt

      - name: Check for Changes
        id: git-status
        run: |
          if git status --porcelain | grep -q "todo.txt"; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.changes == 'true'
        run: |
          git config user.name "$ACTOR_NAME"
          git config user.email "${ACTOR_NAME}@users.noreply.github.com"
          BRANCH_NAME="todo-update-${ITEM}-${{ github.run_id }}"
          git checkout -b "$BRANCH_NAME"
          git add todo.txt
          git commit -m "Add '$ITEM' to todo list by @$ACTOR_NAME"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:refs/heads/$BRANCH_NAME

      - name: Create Pull Request
        if: env.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_BODY="**Todo List Update**

          - **Triggered by:** @$ACTOR_NAME
          - **Item Added:** $ITEM

          **Details:**
          - Adds '$ITEM' to todo.txt for review."

          PR_URL=$(gh pr create \
            --base main \
            --head "todo-update-${ITEM}-${{ github.run_id }}" \
            --title "Add '$ITEM' to todo list by @$ACTOR_NAME" \
            --body "$PR_BODY" | grep -Eo 'https://github.com/[^ ]+')

          echo "PR created at: $PR_URL"
