name: Create PR for Todo Update

on:
  workflow_dispatch:
    inputs:
      item:
        description: 'Item to add to the todo list'
        required: true
        default: 'Review PRs'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Capture Inputs
        run: |
          echo "ACTOR_NAME=${{ github.actor }}" >> $GITHUB_ENV
          echo "ITEM=${{ github.event.inputs.item }}" >> $GITHUB_ENV
          echo "SANITIZED_ITEM=$(echo '${{ github.event.inputs.item }}' | sed 's/ /-/g')" >> $GITHUB_ENV

      - name: Add item to todo list
        run: echo "${{ github.event.inputs.item }}" >> todo.txt

      - name: Check for Changes
        id: git-status
        run: |
          if git status --porcelain | grep -q "todo.txt"; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Commit and create pull request
        if: env.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add '${{ env.ITEM }}' to todo list by @${{ env.ACTOR_NAME }}"
          branch: todo-update-${{ env.SANITIZED_ITEM }}-${{ github.run_id }}
          title: "Add '${{ env.ITEM }}' to todo list by @${{ env.ACTOR_NAME }}"
          body: |
            **Todo List Update**

            - **Triggered by:** @${{ env.ACTOR_NAME }}  
            - **Item Added:** ${{ env.ITEM }}

            **Details:**  
            - Adds '${{ env.ITEM }}' to todo.txt for review.

      - name: Notify user
        run: echo "Pull request created (or updated) successfully."

