name: Greet User Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'guest'

  jobs:
    greet:
      runs-on: ubuntu-latest
      steps:
        - name: Say Hello
          run: echo "Hello, ${{ github.event.inputs.username }}! Welcome to Chick-fil-A's cloud automation!"
