name: Update Todo List

on:
  workflow_dispatch:
    inputs:
      item:
        description: 'Item to add to the todo list'
        required: true
        default: 'Learn GitHub Actions'

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add item to todo list
        run: echo "${{ github.event.inputs.item }}" >> todo.txt

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@users.noreply.github.com"
          git add todo.txt
          git commit -m "Add '${{ github.event.inputs.item }}' to todo list"
          git push
